name: NASAWallpapers
options:
  bundleIdPrefix: com.nasawallpapers
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  NASAWallpapers:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.willhsieh.nasawallpapers
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_NAME: NASA Wallpapers
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        COMBINE_HIDPI_IMAGES: true
        CODE_SIGN_ENTITLEMENTS: Sources/NASAWallpapers.entitlements
    entitlements:
      path: Sources/NASAWallpapers.entitlements
